{% set name = "amazon-sagemaker-sql-execution" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dd0e466dddf7f05a0329307961e779d7f2dfde5d04c7e6623ceb61f9779143a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >=3.8
    - boto3 >=1.28.64
    - pyathena >=3.3.0,<4
    - redshift_connector >=2.1.0,<3
    - aws-embedded-metrics >=3.2.0,<4
    - snowflake-connector-python >=3.8.1,<4.0
    - cryptography >=42.0.0

test:
  imports:
    - amazon_sagemaker_sql_execution
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/amazon-sagemaker-sql-execution/
  summary: 'Provides SQL Execution components for Amazon SageMaker'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kumarnzt
    - gogakoreli
    - varun196
    - HariniNarayanan
